const data = {
    products:[
        {
            _id:'1',
            artist: 'Jimi Hendrix',
            title: 'Electric Ladyland',
            genre: 'Classic Rock',
            image: '/images/electric_ladyland.jpg',
            price: 21.99,
            description: 'album description here',
            format: 'Vinyl',
        },
        {
            _id:'2',
            artist: 'Pink Floyd',
            title: 'Dark Side of the Moon',
            genre: 'Classic Rock',
            image: '/images/Dark_Side_of_the_Moon.png',
            price: 25.99,
            description: 'album description here',
            format: 'Vinyl',
        },
        {
            _id:'3',
            artist: 'Metallica',
            title: 'Ride the Lightning',
            genre: 'Metal',
            image: '/images/Ride_the_lightning.png',
            price: 9.99,
            description: 'album description here',
            format: 'CD',
        },
        {
            _id:'4',
            artist: 'Kanye West',
            title: 'Yeezus',
            genre: 'Hip-Hop/Rap',
            image: '/images/yeezus.jpg',
            price: 7.99,
            description: 'album description here',
            format: 'CD',
        },
        {
            _id:'5',
            artist: 'Miles Davis',
            title: 'Kind of Blue',
            genre: 'Jazz',
            image: '/images/kind_of_blue.jpg',
            price: 6.99,
            description: 'album description here',
            format: 'Cassette',
        },
        {
            _id:'6',
            artist: 'The Beatles',
            title: 'Abbey Road',
            genre: 'Classic Rock',
            image: '/images/abbey_road.jpg',
            price: 30.99,
            description: 'album description here',
            format: 'Vinyl',
        },
    ],
};

export default data;